name: Mobile Test Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: default
          emulator-build: stable

      - name: Install Android System Image
        run: yes | sdkmanager "system-images;android-30;google_apis;x86_64"

      - name: Create Android Emulator
        run: echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n Android -k "system-images;android-30;google_apis;x86_64" --force

      - name: Set ANDROID_AVD_HOME
        run: echo "export ANDROID_AVD_HOME=$HOME/.android/avd" >> $GITHUB_ENV

      - name: Fix Permissions
        run: sudo chmod -R 777 $HOME/.android/avd/

      - name: List Available AVDs
        run: $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list avd

      - name: Start Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd Android -no-accel -no-window -no-audio -no-window -gpu swiftshader_indirect -no-snapshot-load &
          adb wait-for-device
          sleep 60 # Espera extra para garantir que o emulador esteja carregado
          adb exec-out screencap -p > /dev/null # Testa se o emulador está ativo
          adb shell input keyevent 82 || echo "Desbloqueio falhou, tentando continuar assim mesmo"

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium Server
        run: appium &
        
      - name: Install APK
        run: adb install apk/stagfc1.123.39.apk
        
      - name: Run Mobile Tests
        run: npx wdio run wdio.conf.js
